#ifndef TRITON_TOKENS_H
#define TRITON_TOKENS_H

enum triton_token {
    T_ERROR = 256,
    T_NEWLINE,
    T_INDENT,
    T_DEDENT,

    T_IDENTIFIER,
    T_INTEGER,
    T_FLOAT,
    T_COMPLEX,
    T_STRING,

    T_DEF,
    T_RETURN,
    T_IF,
    T_ELIF,
    T_ELSE,
    T_FOR,
    T_WHILE,
    T_IN,
    T_IMPORT,
    T_FROM,
    T_AS,
    T_TRY,
    T_EXCEPT,
    T_FINALLY,
    T_PASS,
    T_BREAK,
    T_CONTINUE,
    T_CLASS,
    T_WITH,
    T_LAMBDA,
    T_YIELD,
    T_ASSERT,
    T_RAISE,
    T_GLOBAL,
    T_NONLOCAL,
    T_AND,
    T_OR,
    T_NOT,
    T_IS,
    T_NONE,
    T_TRUE,
    T_FALSE,

    T_TRITON_JIT,
    T_TRITON_AUTOTUNE,
    T_TRITON_HEURISTICS,
    T_TRITON_DECORATOR,
    T_TRITON_SYMBOL,

    T_TL_CONSTEXPR,
    T_TL_LOAD,
    T_TL_STORE,
    T_TL_ARANGE,
    T_TL_PROGRAM_ID,
    T_TL_CDIV,
    T_TL_WHERE,
    T_TL_DOT,
    T_TL_FULL,
    T_TL_ZEROS,
    T_TL_EXP,
    T_TL_LOG,
    T_TL_SQRT,
    T_TL_RSQRT,
    T_TL_SIGMOID,
    T_TL_ERF,
    T_TL_SIN,
    T_TL_COS,
    T_TL_ABS,
    T_TL_MAXIMUM,
    T_TL_MINIMUM,
    T_TL_SUM,
    T_TL_MAX,
    T_TL_MIN,
    T_TL_ARGMAX,
    T_TL_ARGMIN,
    T_TL_DTYPE,
    T_TL_SYMBOL,

    T_TORCH_SYMBOL,
    T_FUNCTIONAL_SYMBOL,

    T_ARROW,
    T_WALRUS,
    T_ELLIPSIS,
    T_EQ,
    T_NE,
    T_LE,
    T_GE,
    T_LSHIFT,
    T_RSHIFT,
    T_POWER,
    T_FLOORDIV,
    T_PLUS_ASSIGN,
    T_MINUS_ASSIGN,
    T_STAR_ASSIGN,
    T_SLASH_ASSIGN,
    T_PERCENT_ASSIGN,
    T_AMP_ASSIGN,
    T_PIPE_ASSIGN,
    T_CARET_ASSIGN,
    T_LSHIFT_ASSIGN,
    T_RSHIFT_ASSIGN,
    T_POWER_ASSIGN,
    T_FLOORDIV_ASSIGN,

    T_ASSIGN,
    T_LT,
    T_GT,
    T_PLUS,
    T_MINUS,
    T_STAR,
    T_SLASH,
    T_PERCENT,
    T_AMP,
    T_PIPE,
    T_CARET,
    T_TILDE,
    T_DOT,
    T_COMMA,
    T_COLON,
    T_SEMICOLON,
    T_AT,
    T_BACKSLASH,

    T_LPAREN,
    T_RPAREN,
    T_LBRACKET,
    T_RBRACKET,
    T_LBRACE,
    T_RBRACE
};

extern char triton_token_text[];
extern int triton_token_line;
extern int triton_token_column;

int yylex(void);
const char *triton_token_name(int token);

#endif
